// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package model

import ()

type BbcStatus struct {
	NetworkID   uint64
	Height      uint64
	BbcValsHash string
	BscValsHash string
	StakeModSeq uint64
	SyncedAt    uint64
}
